# -*- coding: utf-8 -*-
"""HelloWord.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhzuLLvv8wdcfXvP7LZqPjQFhOBhAIz2
"""

import pandas as pd

url = "https://raw.githubusercontent.com/KeithGalli/pandas/master/pokemon_data.csv"
df = pd.read_csv(url)

df.head()

df["Total"] = df[["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]].sum(axis=1)

df.sort_values("Total", ascending=False).head(10)

df_normal = df[~df["Name"].str.contains("Mega")]
df_normal = df_normal[~df_normal["Name"].str.contains("Primal")]

df_normal.sort_values("Total", ascending=False).head(10)

"""# Análise de Dados do Universo Pokémon com Python

## Objetivo
Este projeto tem como objetivo analisar os atributos dos Pokémon para identificar padrões de força e verificar se Pokémon lendários possuem vantagem estatística em relação aos demais.

A análise foi realizada utilizando Python e a biblioteca Pandas.

## 1. Carregando os dados

Nesta etapa, carregamos o conjunto de dados contendo informações sobre os Pokémon, como HP, Attack, Defense, Speed, geração e classificação como lendário ou não.

O objetivo é preparar os dados para análise.

## 2. Criando a variável "Total"

Para facilitar a comparação entre os Pokémon, foi criada uma nova coluna chamada "Total", que representa a soma dos principais atributos:

HP + Attack + Defense + Sp. Atk + Sp. Def + Speed

Essa variável permite medir a força geral de cada Pokémon de maneira consolidada.

## 3. Identificando os Pokémon mais fortes

Nesta etapa, os Pokémon foram organizados do maior para o menor valor da variável "Total", permitindo identificar quais apresentam maior força geral.

## 4. Comparação entre lendários e não lendários

Nesta etapa, foi calculada a média da variável "Total" para dois grupos: Pokémon lendários e não lendários.

O objetivo é verificar se existe diferença significativa de poder entre esses dois grupos.

## Conclusão

A análise mostrou que:

- Pokémon lendários possuem, em média, maior valor total de atributos.
- A variável "Total" permite comparar a força geral de forma objetiva.
- A análise de dados possibilita identificar padrões que não são facilmente percebidos apenas pela observação direta.

Este projeto demonstra a aplicação de Python e Pandas para exploração e análise de dados estruturados.
"""